// Mock document data for Phase A — replace with API calls when backend is ready

export const MOCK_DOCUMENTS = [
  {
    id: 'doc-1',
    display_name: 'WINZ Benefit Review Letter',
    internal_ref: 'MSD-BRL-2026',
    category: 'MSD / Benefits',
    description: 'Standard MSD letter sent when a benefit is being reviewed.',
    status: 'active',
    version_number: 2,
    file_name: 'winz-benefit-review-2026.pdf',
    file_size: 248000,
    file_url: '#',
    uploaded_by: { id: '1', name: 'Emily Hill' },
    uploaded_at: '2026-05-12T09:14:00Z',
    approved_by: { id: '1', name: 'Emily Hill' },
    approved_at: '2026-05-13T10:30:00Z',
    approval_note: 'Reviewed and matches current MSD template.',
    published_by: { id: '1', name: 'Emily Hill' },
    published_at: '2026-05-13T11:00:00Z',
    deactivated_by: null,
    deactivated_at: null,
    deactivation_reason: null,
    sort_order: 1,
    created_at: '2026-05-12T09:14:00Z',
    updated_at: '2026-05-13T11:00:00Z',
  },
  {
    id: 'doc-2',
    display_name: 'Tenancy Agreement (Standard)',
    internal_ref: 'PROP-TA-001',
    category: 'Property / Tenancy',
    description: 'Standard residential tenancy agreement for new tenants.',
    status: 'active',
    version_number: 1,
    file_name: 'tenancy-agreement-standard.pdf',
    file_size: 512000,
    file_url: '#',
    uploaded_by: { id: '1', name: 'Emily Hill' },
    uploaded_at: '2026-05-20T14:00:00Z',
    approved_by: { id: '1', name: 'Emily Hill' },
    approved_at: '2026-05-21T09:00:00Z',
    approval_note: null,
    published_by: { id: '1', name: 'Emily Hill' },
    published_at: '2026-05-21T09:15:00Z',
    deactivated_by: null,
    deactivated_at: null,
    deactivation_reason: null,
    sort_order: 2,
    created_at: '2026-05-20T14:00:00Z',
    updated_at: '2026-05-21T09:15:00Z',
  },
  {
    id: 'doc-3',
    display_name: 'School Enrolment Form',
    internal_ref: 'SCH-ENR-2026',
    category: 'General Government',
    description: 'Ministry of Education standard enrolment form for primary schools.',
    status: 'approved',
    version_number: 1,
    file_name: 'school-enrolment-2026.pdf',
    file_size: 189000,
    file_url: '#',
    uploaded_by: { id: '1', name: 'Emily Hill' },
    uploaded_at: '2026-06-01T10:00:00Z',
    approved_by: { id: '1', name: 'Emily Hill' },
    approved_at: '2026-06-03T11:30:00Z',
    approval_note: 'Confirmed matches 2026 MoE template.',
    published_by: null,
    published_at: null,
    deactivated_by: null,
    deactivated_at: null,
    deactivation_reason: null,
    sort_order: null,
    created_at: '2026-06-01T10:00:00Z',
    updated_at: '2026-06-03T11:30:00Z',
  },
  {
    id: 'doc-4',
    display_name: 'IRD Tax Code Declaration',
    internal_ref: null,
    category: 'IRD / Tax',
    description: null,
    status: 'draft',
    version_number: 1,
    file_name: 'ird-tax-code-ir330.pdf',
    file_size: 95000,
    file_url: '#',
    uploaded_by: { id: '1', name: 'Emily Hill' },
    uploaded_at: '2026-06-04T15:22:00Z',
    approved_by: null,
    approved_at: null,
    approval_note: null,
    published_by: null,
    published_at: null,
    deactivated_by: null,
    deactivated_at: null,
    deactivation_reason: null,
    sort_order: null,
    created_at: '2026-06-04T15:22:00Z',
    updated_at: '2026-06-04T15:22:00Z',
  },
  {
    id: 'doc-5',
    display_name: 'ACC Claim Form (ACC45)',
    internal_ref: 'ACC-45',
    category: 'Health / Patient',
    description: 'Standard ACC injury claim form.',
    status: 'inactive',
    version_number: 1,
    file_name: 'acc-claim-acc45.pdf',
    file_size: 320000,
    file_url: '#',
    uploaded_by: { id: '1', name: 'Emily Hill' },
    uploaded_at: '2026-04-10T09:00:00Z',
    approved_by: { id: '1', name: 'Emily Hill' },
    approved_at: '2026-04-11T10:00:00Z',
    approval_note: null,
    published_by: { id: '1', name: 'Emily Hill' },
    published_at: '2026-04-11T10:30:00Z',
    deactivated_by: { id: '1', name: 'Emily Hill' },
    deactivated_at: '2026-05-30T14:00:00Z',
    deactivation_reason: 'Replaced by updated 2026 version. Uploading new file shortly.',
    sort_order: null,
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-05-30T14:00:00Z',
  },
]

export const MOCK_ACTIVITY = [
  {
    id: 'act-1',
    timestamp: '2026-06-04T15:22:00Z',
    user: { id: '1', name: 'Emily Hill' },
    action: 'Uploaded a new document: IRD Tax Code Declaration (v1)',
    document_id: 'doc-4',
    document_name: 'IRD Tax Code Declaration',
    detail: 'v1',
  },
  {
    id: 'act-2',
    timestamp: '2026-06-03T11:30:00Z',
    user: { id: '1', name: 'Emily Hill' },
    action: 'Marked School Enrolment Form as approved',
    document_id: 'doc-3',
    document_name: 'School Enrolment Form',
    detail: 'v1 — Note: Confirmed matches 2026 MoE template.',
  },
  {
    id: 'act-3',
    timestamp: '2026-05-30T14:00:00Z',
    user: { id: '1', name: 'Emily Hill' },
    action: 'Deactivated ACC Claim Form (ACC45)',
    document_id: 'doc-5',
    document_name: 'ACC Claim Form (ACC45)',
    detail: 'Reason: Replaced by updated 2026 version. Uploading new file shortly.',
  },
  {
    id: 'act-4',
    timestamp: '2026-05-21T09:15:00Z',
    user: { id: '1', name: 'Emily Hill' },
    action: 'Published Tenancy Agreement (Standard) to the active list',
    document_id: 'doc-2',
    document_name: 'Tenancy Agreement (Standard)',
    detail: 'v1',
  },
  {
    id: 'act-5',
    timestamp: '2026-05-13T11:00:00Z',
    user: { id: '1', name: 'Emily Hill' },
    action: 'Published WINZ Benefit Review Letter to the active list',
    document_id: 'doc-1',
    document_name: 'WINZ Benefit Review Letter',
    detail: 'v2',
  },
]

export function formatFileSize(bytes) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function formatDate(iso) {
  if (!iso) return '—'
  const d = new Date(iso)
  return d.toLocaleDateString('en-NZ', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}
